<?php

use Illuminate\Database\Seeder;

class ConfigsTableSeeder extends Seeder {

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run() {
        \DB::table('configs')->delete();

        \DB::table('configs')->insert([
            0  => [
                'id'         => 1,
                'name'       => 'WEB_NAME',
                'value'      => '加藤非博客',
                'created_at' => '2121-07-5 12:12:00',
                'updated_at' => '2121-07-5 12:12:00',
                'deleted_at' => NULL,
            ],
            1  => [
                'id'         => 2,
                'name'       => 'WEB_KEYWORDS',
                'value'      => '个人博客,博客模板,thinkphp,laravel博客,php博客,技术博客,加藤非',
                'created_at' => '2121-07-5 12:12:00',
                'updated_at' => '2021-07-21 22:51:54',
                'deleted_at' => NULL,
            ],
            2  => [
                'id'         => 3,
                'name'       => 'WEB_DESCRIPTION',
                'value'      => '加藤非的php博客,个人技术博客,bjyblog,bjyadmin官方网站',
                'created_at' => '2121-07-5 12:12:00',
                'updated_at' => '2121-07-5 12:12:00',
                'deleted_at' => NULL,
            ],
            3  => [
                'id'         => 4,
                'name'       => 'WEB_STATUS',
                'value'      => '1',
                'created_at' => '2121-07-5 12:12:00',
                'updated_at' => '2121-07-5 12:12:00',
                'deleted_at' => NULL,
            ],
            4  => [
                'id'         => 5,
                'name'       => 'BLACK_WHITE',
                'value'      => '0',
                'created_at' => '2121-07-5 12:12:00',
                'updated_at' => '2121-07-5 12:12:00',
                'deleted_at' => NULL,
            ],
            5  => [
                'id'         => 6,
                'name'       => 'WATER_TYPE',
                'value'      => '1',
                'created_at' => '2121-07-5 12:12:00',
                'updated_at' => '2121-07-5 12:12:00',
                'deleted_at' => NULL,
            ],
            6  => [
                'id'         => 7,
                'name'       => 'TEXT_WATER_WORD',
                'value'      => 'linkgeek.com',
                'created_at' => '2121-07-5 12:12:00',
                'updated_at' => '2121-07-5 12:12:00',
                'deleted_at' => NULL,
            ],
            7  => [
                'id'         => 8,
                'name'       => 'TEXT_WATER_TTF_PTH',
                'value'      => './Public/static/font/ariali.ttf',
                'created_at' => '2121-07-5 12:12:00',
                'updated_at' => '2121-07-5 12:12:00',
                'deleted_at' => NULL,
            ],
            8  => [
                'id'         => 9,
                'name'       => 'TEXT_WATER_FONT_SIZE',
                'value'      => '15',
                'created_at' => '2121-07-5 12:12:00',
                'updated_at' => '2121-07-5 12:12:00',
                'deleted_at' => NULL,
            ],
            9  => [
                'id'         => 10,
                'name'       => 'TEXT_WATER_COLOR',
                'value'      => '#008CBA',
                'created_at' => '2121-07-5 12:12:00',
                'updated_at' => '2121-07-5 12:12:00',
                'deleted_at' => NULL,
            ],
            10 => [
                'id'         => 11,
                'name'       => 'TEXT_WATER_ANGLE',
                'value'      => '0',
                'created_at' => '2121-07-5 12:12:00',
                'updated_at' => '2121-07-5 12:12:00',
                'deleted_at' => NULL,
            ],
            11 => [
                'id'         => 12,
                'name'       => 'TEXT_WATER_LOCATE',
                'value'      => '9',
                'created_at' => '2121-07-5 12:12:00',
                'updated_at' => '2121-07-5 12:12:00',
                'deleted_at' => NULL,
            ],
            12 => [
                'id'         => 13,
                'name'       => 'IMAGE_WATER_PIC_PTAH',
                'value'      => './Upload/image/logo/logo.png',
                'created_at' => '2121-07-5 12:12:00',
                'updated_at' => '2121-07-5 12:12:00',
                'deleted_at' => NULL,
            ],
            13 => [
                'id'         => 14,
                'name'       => 'IMAGE_WATER_LOCATE',
                'value'      => '9',
                'created_at' => '2121-07-5 12:12:00',
                'updated_at' => '2121-07-5 12:12:00',
                'deleted_at' => NULL,
            ],
            14 => [
                'id'         => 15,
                'name'       => 'IMAGE_WATER_ALPHA',
                'value'      => '80',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            15 => [
                'id'         => 16,
                'name'       => 'WEB_CLOSE_WORD',
                'value'      => '网站升级中，请稍后访问！',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            16 => [
                'id'         => 17,
                'name'       => 'WEB_ICP_NUMBER',
                'value'      => '粤ICP备21009515号-1',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            17 => [
                'id'         => 18,
                'name'       => 'ADMIN_EMAIL',
                'value'      => '941192051@qq.com',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2021-06-21 22:51:54',
                'deleted_at' => NULL,
            ],
            18 => [
                'id'         => 19,
                'name'       => 'COPYRIGHT_WORD',
                'value'      => '本文为加藤非原创文章,转载无需和我联系,但请注明来自<a href="http://linkgeek.com">加藤非博客</a>http://linkgeek.com',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2021-06-21 22:51:54',
                'deleted_at' => NULL,
            ],
            19 => [
                'id'         => 20,
                'name'       => 'QQ_APP_ID',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            20 => [
                'id'         => 21,
                'name'       => 'CHANGYAN_APP_ID',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            21 => [
                'id'         => 22,
                'name'       => 'CHANGYAN_CONF',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            22 => [
                'id'         => 23,
                'name'       => 'WEB_STATISTICS',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2021-06-21 22:51:54',
                'deleted_at' => NULL,
            ],
            23 => [
                'id'         => 24,
                'name'       => 'CHANGEYAN_RETURN_COMMENT',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            24 => [
                'id'         => 25,
                'name'       => 'AUTHOR',
                'value'      => '加藤非',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            25 => [
                'id'         => 26,
                'name'       => 'QQ_APP_KEY',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            26 => [
                'id'         => 27,
                'name'       => 'CHANGYAN_COMMENT',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            27 => [
                'id'         => 28,
                'name'       => 'BAIDU_SITE_URL',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2021-06-21 22:51:54',
                'deleted_at' => NULL,
            ],
            28 => [
                'id'         => 29,
                'name'       => 'DOUBAN_API_KEY',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            29 => [
                'id'         => 30,
                'name'       => 'DOUBAN_SECRET',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            30 => [
                'id'         => 31,
                'name'       => 'RENREN_API_KEY',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            31 => [
                'id'         => 32,
                'name'       => 'RENREN_SECRET',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            32 => [
                'id'         => 33,
                'name'       => 'SINA_API_KEY',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            33 => [
                'id'         => 34,
                'name'       => 'SINA_SECRET',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            34 => [
                'id'         => 35,
                'name'       => 'KAIXIN_API_KEY',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            35 => [
                'id'         => 36,
                'name'       => 'KAIXIN_SECRET',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            36 => [
                'id'         => 37,
                'name'       => 'SOHU_API_KEY',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            37 => [
                'id'         => 38,
                'name'       => 'SOHU_SECRET',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            38 => [
                'id'         => 39,
                'name'       => 'GITHUB_CLIENT_ID',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            39 => [
                'id'         => 40,
                'name'       => 'GITHUB_CLIENT_SECRET',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            40 => [
                'id'         => 41,
                'name'       => 'IMAGE_TITLE_ALT_WORD',
                'value'      => '加藤非博客',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            41 => [
                'id'         => 42,
                'name'       => 'EMAIL_SMTP',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            42 => [
                'id'         => 43,
                'name'       => 'EMAIL_USERNAME',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            43 => [
                'id'         => 44,
                'name'       => 'EMAIL_PASSWORD',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            44 => [
                'id'         => 45,
                'name'       => 'EMAIL_FROM_NAME',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            45 => [
                'id'         => 46,
                'name'       => 'COMMENT_REVIEW',
                'value'      => '0',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            46 => [
                'id'         => 47,
                'name'       => 'COMMENT_SEND_EMAIL',
                'value'      => '1',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            47 => [
                'id'         => 48,
                'name'       => 'EMAIL_RECEIVE',
                'value'      => '',
                'created_at' => '2121-07-5 12:12:01',
                'updated_at' => '2121-07-5 12:12:01',
                'deleted_at' => NULL,
            ],
            48 => [
                'id'         => 49,
                'name'       => 'WEB_TITLE',
                'value'      => '加藤非博客,技术博客,个人博客模板, php博客系统',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            49 => [
                'id'         => 50,
                'name'       => 'QQ_QUN_ARTICLE_ID',
                'value'      => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            50 => [
                'id'         => 51,
                'name'       => 'QQ_QUN_NUMBER',
                'value'      => '88199093',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            51 => [
                'id'         => 52,
                'name'       => 'QQ_QUN_CODE',
                'value'      => '<a target="_blank" href="//shang.qq.com/wpa/qunwpa?idkey=bba3fea90444ee6caf1fb1366027873fe14e86bada254d41ce67768fadd729ee"><img border="0" src="//pub.idqqimg.com/wpa/images/group.png" alt="加藤非博客群" title="加藤非博客群"></a>',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            52 => [
                'id'         => 53,
                'name'       => 'QQ_QUN_OR_CODE',
                'value'      => '/uploads/images/default.png',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
        ]);
    }
}
